import { Product } from "./product";

export interface GPU extends Product {
  chipSpeed: number,
  chipMemoriSpeed: number,
  recomendedTdp:number,
  chipset:string,
  chipsetfamily:string,
  cooling:string,
  ventcount:number,
  memoriAmount:number,
  memoryType:string,
  memorySavszelesseg:number,
  maxFelbontas:string,
  DirectX:string,
  TapCsatlakozo:string,
  LED:boolean,
  color:string,
  usedTech:string[],
  DLSS: string[],
  VGA:Map<boolean,number>,
  DVI:Map<boolean,number>,
  HDMI:Map<boolean,number>,
  Display:Map<boolean,number>,
  Type_C:Map<boolean,number>,
  szelesseg:number,
  hosszusag:number,
  vastagsag:number,
}
